In [10]:
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

In [11]:
points= np.arange(-5,5,0.01)


In [12]:
dx,dy=np.meshgrid(points,points)

In [14]:
dx

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [15]:
z=(np.sin(dx)+np.sin(dy))
z

array([[ 1.91784855e+00,  1.92063718e+00,  1.92332964e+00, ...,
        -8.07710558e-03, -5.48108704e-03, -2.78862876e-03],
       [ 1.92063718e+00,  1.92342581e+00,  1.92611827e+00, ...,
        -5.28847682e-03, -2.69245827e-03, -5.85087534e-14],
       [ 1.92332964e+00,  1.92611827e+00,  1.92881072e+00, ...,
        -2.59601854e-03, -5.63993297e-14,  2.69245827e-03],
       ...,
       [-8.07710558e-03, -5.28847682e-03, -2.59601854e-03, ...,
        -1.93400276e+00, -1.93140674e+00, -1.92871428e+00],
       [-5.48108704e-03, -2.69245827e-03, -5.63993297e-14, ...,
        -1.93140674e+00, -1.92881072e+00, -1.92611827e+00],
       [-2.78862876e-03, -5.85087534e-14,  2.69245827e-03, ...,
        -1.92871428e+00, -1.92611827e+00, -1.92342581e+00]])

In [16]:
plt.imshow(z)

In [18]:
plt.imshow(z)
plt.colorbar()
plt.title('plot for sin(x)+sin(y)')

Text(0.5, 1.0, 'plot for sin(x)+sin(y)')

In [19]:
A=np.array([1,2,3,4])
B=np.array([100,200,300,400])

In [20]:
condition=np.array([True,True,False,False])

In [25]:
answer=[(A_val if condition else B_val)for A_val,B_val,condition in zip (A,B ,condition)]


[1, 2, 300, 400]

In [ ]:
answer


In [24]:
answer2=np.where(condition ,A,B)
answer2

array([  1,   2, 300, 400])

In [26]:
from numpy.random import randn

In [27]:
arr=randn(5,5)
arr

array([[-2.54450795,  1.63343515,  0.70345826,  0.36153459, -1.81378065],
       [ 0.09845684, -0.2412518 ,  0.25102427,  0.62252292,  0.47178221],
       [-0.43995252, -0.06854274, -0.93263956, -0.30812031,  0.26593191],
       [-0.31950842, -0.40537687, -0.2522353 , -0.08752332, -0.98737726],
       [ 0.2924554 , -1.43983556, -1.11459565, -1.14092334, -0.27597824]])

In [28]:
np.where(arr<0,0 ,arr)

array([[0.        , 1.63343515, 0.70345826, 0.36153459, 0.        ],
       [0.09845684, 0.        , 0.25102427, 0.62252292, 0.47178221],
       [0.        , 0.        , 0.        , 0.        , 0.26593191],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.2924554 , 0.        , 0.        , 0.        , 0.        ]])